repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      exclude: \.py-tpl$
      args: ["pipcx", "test","--config", "pyproject.toml", "--experimental-string-processing"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["pipcx", "test"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade