[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    |.tox,
    |.git,
    |__pycache__,
    |docs/source/conf.py,
    |build,
    |dist,
    |tests/fixtures/*,
    |*.pyc,
    |*.egg-info,
    |.cache,
    |.eggs
    |venv
    |test
    |*__init__.py
    |manual_testing
)/
'''
[flake8]
ignore = ["D203", "W503", "E203", "N818", "E501"]
max-line-length = 79
max-complexity = 18
exclude = '''
/(
    |.tox,
    |.git,
    |__pycache__,
    |docs/source/conf.py,
    |build,
    |dist,
    |tests/fixtures/*,
    |*.pyc,
    |*.egg-info,
    |.cache,
    |.eggs
    |venv
    |test
    |*__init__.py
    |manual_testing
)/
'''
[tool.pylint]
ignore-patterns="__init__.py"
disable=["E1101","E1133"]