[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.env.*
  | \env
  | venv
  | _build
  | build
  | dist
  | examples
  | docs
  | manual_testing
)\
'''

[flake8]
ignore = ["D203", "W503", "E203", "N818", "E501"]
max-line-length = 79
max-complexity = 18
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | venv
  | manual_testing
)/
'''

[tool.pylint]
ignore-patterns="__init__.py"
disable=["E1101","E1133"]